Pass the calendar prop to `formatDate`
Shopify/quilt pull request #2463
Opened 2022-11-10 17:22 UTC by adam-felix-shopify

## Description

[FormatJS's Intl.DateTimeFormat](https://formatjs.io/docs/polyfills/intl-datetimeformat/) only supports the Gregorian calendar.  These changes enforce that.

Fixes (or at least it should) crashing issues on React Native for the [mobile repo](https://github.com/Shopify/mobile)

### Mobile Tophat:

__Setup__:

1. Change an iOS device's region to Thailand
1. Change the device's language to Thai
1. In the mobile repo, run
```
yarn add @shopify/react-i18n@0.0.0-snapshot-20221111164351
```
1. After that successfully completes, run `dev up`
1. Run `dev react-native start --reset-cache`
    * __Note__:  `--reset-cache` may not be needed
1. Run the app (either by building in Xcode or `dev react-native run-ios`

__Test__:

1. Navigate to the online store section of the store tab
    * __Expected behaviour__:  No crashes occur

#### Video of this test:

__Before__:

https://user-images.githubusercontent.com/99921496/201183803-30c175b9-af29-41ac-8087-01ac8bb8fb57.mov

__After__:

https://user-images.githubusercontent.com/99921496/201183933-1b05abf3-14d8-4539-a9b0-a9a36d4532da.mov

2022-11-10 17:22 UTC, adam-felix-shopify commented
/snapit

2022-11-10 17:27 UTC, atesgoral commented on packages/dates/src/utilities/formatDate.ts
> +  calendar: 'gregory',
It would be a nice to add comment about why this restriction is being added so that we can remember to remove it once there's wider support.

2022-11-10 18:39 UTC, adam-felix-shopify commented
/snapit

2022-11-10 19:11 UTC, BPScott commented
How come you're relying on the FormatJS's polyfill? Support for Intl.DateTimeFormat is available on [all modern platforms](https://caniuse.com/?search=datetimeformat). What browser engines are you targeting that need this polyfill?

2022-11-10 20:29 UTC, adam-felix-shopify commented
> How come you're relying on the FormatJS's polyfill? Support for Intl.DateTimeFormat is available on [all modern platforms](https://caniuse.com/?search=datetimeformat). What browser engines are you targeting that need this polyfill?

@BPScott:  I'm not sure.  We're using `react-i18n` with React Native.

2022-11-10 21:38 UTC, BPScott requested changes
Looks like it came in when you adopted Hermes on 2022-09-27 in https://github.com/Shopify/mobile/pull/8541, and [Hermes iOS support for Intl gets added in react-native 0.70.0](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#0700)

---

This change is a breaking change. It changes the date rendering behaviour for locales that do not use the gregorian calendar by default and that seems very suprising and unexpected. It also seems like a bad merchant experience as dates are no longer in the form that they are used to based upon their locale.

Running `console.log((new Intl.DateTimeFormat('th-TH')).resolvedOptions().calendar);` suggests that the default Thai calendar is the Buddhist calendar which [wikipedia](https://en.wikipedia.org/wiki/Buddhist_calendar) suggests is similar to the gergorian calendar except it uses a different year epoch. I suspect this change would stop your app from crashing thanks to your polyfill not supporting gregorian calendars but you, and every other app that consumes these packages would be left with Thai merchants wondering why their years are 543 years different to what they expect - the Gregorian year 2022 is represented as year 2565 in the Thai buddhist calendar.

Because of this change in merchant experience I do not think this is a fix that should be merged. This issue does not affect users in supported browsers. It only affect app authors who are using polyfills for Intl.DateTimeFormat because they use Hermes and react-native <0.70.0.

I think the right fix for this is in the mobile repo, which should remove their `Intl.DateTimeFormat` polyfill. It should either revert its Hermes support, or update to React Native 0.70.0 which adds support for these I18n APIs in iOS. A quick-fix while you update your react-native version would be to continue useing the snapshot you have created as part of this PR - assuming you consider this year change on iOS devices only acceptable.

2022-11-11 16:42 UTC, adam-felix-shopify commented
/snapit

2022-11-11 17:21 UTC, adam-felix-shopify commented
I updated the PR to pass calendar through to calls of `formatDate` and updated the browser related constant to be a function that takes options.

2022-11-11 22:15 UTC, gvarandas commented on packages/dates/src/utilities/formatDate.ts
> +    ro != null && options.hour12 === false && ro.hourCycle != null;
```suggestion
    resolvedOptions != null && options.hour12 === false && ro.hourCycle != null;
```

2022-11-14 14:18 UTC, daehn approved these changes
🎩 ✅  after the adjustments.

https://user-images.githubusercontent.com/4603353/201683109-d0171084-985d-48a9-a6d5-d9dc7f2b2254.mp4

2022-11-14 21:34 UTC, BPScott requested changes
I'm more amenable to letting folks override the calendar compared to the prior approach as it avoids the breaking change, thought this still feels like a fix for a temporary issue (till mobile apps adopt RN 0.70) rather than a long-term feature that we'd like to continue to support.

Having to explictly override the calendar for every formatDate call an application uses feels like a poor developer experience - it requires lots of updates to get things working, is error prone as it would be easy to miss setting this if a new call to formatDate is added (and once you forgot one, bang runtime errors in Thai), and once it is no longer needed you've got to go and remove every `calendar: 'gregory'` usage.


Would you be open to the idea of maintaining a fork of `@shopify/dates` that forces the usage of the gregorian calendar (i.e. what the original PR did)? That'd basically be changing this PR back to its original state, and using the snapshot package generated by `/snapit`. If at some point in the future we add other updates to `@shopify/dates` (unlikely, it is a very stable package) then it'd be a case of rebasing this PR and running snapit again.

Alternatively you could use [patch-package](https://www.npmjs.com/package/patch-package) to apply the "force the gregorian calendar" patch as part of installing `@shopify/dates` into the shopify/mobile codebase to make it so the calendar is forced to Gregorian within the context of mobile.

2022-11-14 21:34 UTC, BPScott commented on packages/dates/src/utilities/formatDate.ts
> +  Intl.DateTimeFormat('en', {
Why does this need to be changed? 

I feel pretty certain that `Intl.DateTimeFormat('en', {hour: 'numeric'}).resolvedOptions()` would always result in a gregorian calendar. We never call `.format` on the result of this, so it seems like it wouldn't ever be an issue in the Thai locale.


If my expectation is right and this is not needed, then nothing in this file needs to be changed.

2022-11-14 21:34 UTC, BPScott commented on packages/react-i18n/src/i18n.ts
> +          return this.formatDate(date, {
This seems to be just a whitespace change for the sake of it. Can we revert it to make the diff easier to review?

2022-11-14 21:34 UTC, BPScott commented on packages/react-i18n/src/i18n.ts
> +    return formatDate(date, locale, {
This seems to be just a whitespace change for the sake of it. Can we revert it to make the diff easier to review?

2022-11-30 20:11 UTC, adam-felix-shopify commented
We're going to go ahead with the patch approach and close this PR.

2022-11-30 20:11 UTC, closed without merging